### ISSUE TITLE
How can I open a specific component of my React Native application from an Native Android Activity in Java

### ISSUE THREAD

**Issue by Aravind-WMG** [hudl/react-native-android-fragment#17]
I would like to know whether this lib will be helpful for the below task.

> An Android app is integrated with React Native(RN) following this doc, where page A is in Android and page B is in RN. On click of a button in page A, RN activity started and page B get loaded..so my Question is how the button on page A can be RN component or How can I open a specific component of my React Native application from a Native Android Activity in Java?

More here : https://github.com/facebook/react-native/issues/21128

**Comment by jpshelley** [comment]
Hi @Aravind-WMG, that is a great use case for this library. Hudl follows a similar pattern, where different features are written in Message. We use a single Activity for most of the app and different screens are fragments. This allows us to keep our same architecture and create React Native Android Fragments.

> how the button on page A can be RN component

If you wanted to use this library, the button on page A would have to be a fragment inside of a larger activity. While ideally that button should just be a `View`, I'm not sure how you could use a React Native Component as a single View in a native Android Activity, but wrapping that in a Fragment could work. I haven't tested it personally.

> How can I open a specific component of my React Native application from a Native Android Activity

This is exactly what this library was built for. Check out the [example](https://github.com/hudl/react-native-android-fragment/blob/f74063965e10d78924444a402993d04286ff2983/example/android/app/src/main/java/com/example/MainActivity.java#L21). While it doesn't showcase navigating from a native Activity to a React Native screen, it does show how you can create a React Native Fragment, and then you can follow the Android Documentation to do the rest.

Hope that helps.
