### ISSUE TITLE
OnDestroy clears ReactNativeHost when other Fragment is still using it

### ISSUE THREAD

**Issue by ddudek** [hudl/react-native-android-fragment#18]
Scenario:
1. Create two ReactFragments, A and B, on a tab view for example
2. A is visible (resumed), B is hidden (paused)
3. Hide fragment A, show B
4. Destroy fragment B, onDestroy clears the ReactNativeHost since the A is hidden and not actively using it (reactInstanceMgr.getLifecycleState() returns BEFORE_RESUME): 

```
@Override
    public void onDestroy() {
        super.onDestroy();
        if (mReactRootView != null) {
            mReactRootView.unmountReactApplication();
            mReactRootView = null;
        }
        if (getReactNativeHost().hasInstance()) {
            ReactInstanceManager reactInstanceMgr = getReactNativeHost().getReactInstanceManager();

            // onDestroy may be called on a ReactFragment after another ReactFragment has been
            // created and resumed with the same React Instance Manager. Make sure we only clean up
            // host's React Instance Manager if no other React Fragment is actively using it.
            if (reactInstanceMgr.getLifecycleState() != LifecycleState.RESUMED) {
                reactInstanceMgr.onHostDestroy(getActivity());
                getReactNativeHost().clear();
            }
        }
    }
```
5. Show A back again, try to interact with it

Result:
```
10-16 11:38:59.890 9618-9618/com.someapp.android W/unknown:ReactNative: Unable to dispatch touch to JS as the catalyst instance has not been attached
10-16 11:38:59.891 9618-9618/com.someapp.android W/unknown:ReactNative: Unable to dispatch touch to JS as the catalyst instance has not been attached
10-16 11:38:59.892 9618-9618/com.someapp.android W/unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
10-16 11:38:59.906 9618-9618/com.someapp.android W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {edf0718} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {edf0718} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:59)
        at com.facebook.react.bridge.ReactContext.runOnJSQueueThread(ReactContext.java:297)
        at com.facebook.react.uimanager.events.EventDispatcher$ScheduleDispatchFrameCallback.doFrame(EventDispatcher.java:285)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:635)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
10-16 11:38:59.907 9618-9618/com.someapp.android W/unknown:ReactNative: Unable to dispatch touch to JS as the catalyst instance has not been attached
10-16 11:38:59.929 9618-9618/com.someapp.android W/unknown:ReactNative: Unable to dispatch touch to JS as the catalyst instance has not been attached
10-16 11:38:59.940 9618-9618/com.someapp.android W/unknown:ReactNative: Unable to dispatch touch to JS as the catalyst instance has not been attached
```

When removing the `getReactNativeHost().clear();` everything works fine.

Any idea for the proper solution or workaround? I'm keen to contribute if you can point the proper solution.

**Comment by ddudek** [comment]
Maybe the React fragment should not use `onHostResume(...)`, `onHostPaused(...)`, `onHostDestroy()` at all if there's more than one ReactFragment attached to the same activity? This way one fragment can call onPause and onDestroy, and another one still using the same host without noticing it. It seems that it should be used for Activity callbacks.

I'm currently testing a solution with removing all the "onHost...(activity)" from ReactFragment, and using `registerActivityLifecycleCallbacks` in Application class to send all the lifecycle callbacks to ReactInstanceManager, with keeping just the `mReactRootView.unmountReactApplication();` in the ReactFragment. 
Does it make sense? (i'm not that familiar with ReactNative internals...)

**Comment by jpshelley** [comment]
Thanks for filing the defect mentioned @ddudek! Our original plan was to stay as close to the pattern that the `ReactActivity` and [ReactActivityDelegate](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java) followed, so moving to the Application class deviates from that a bit.

_However_, if it makes the code easier to read, understand, and more stable than I'm all for it. Feel free to submit a PR in the meantime, as I won't have any bandwidth until November. 

With the changes I would also suggest adding a new example in the example folder showing the pattern mentioned as well.

**Comment by shareme** [comment]
glad I found your comments on a proposed solution as I might be hired in the next few days at a startup and this is the first issue I have to tackle.

**Comment by jpshelley** [comment]
It sounds like #22 is having a similar problem as well, so wanted to make sure we work together on a solution.

**Comment by ericmgoeken** [comment]
Some info, but not a solution. 

The best way to know if the InstanceManager should be cleared is when its  mAttachedRootViews is zero. But that property is private and the onDestroy method cannot check if it was the last View to get destroyed.

**Comment by jpshelley** [comment]
@ddudek Thanks for filing this issue. We'll be officially deprecating this repo now that Hudl has upgraded and can take advantage of `react-native`'s official [ReactFragment](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java)

If you believe the official `ReactFragment` also needs this support I would suggest opening a PR there! https://github.com/facebook/react-native/pulls
