### ISSUE TITLE
onCreateView makes a new view every time

### ISSUE THREAD

**Issue by ericmgoeken** [hudl/react-native-android-fragment#22]
If a Fragment is displayed again from the back stack onCreateView is called. A new view is created instead of using the one that is already there.

**Comment by jpshelley** [comment]
@ericmgoeken I saw you closed your original PR. If you think this is still an issue, you should feel welcome to leave it as open. We haven't come across this use case as most of our React Native Fragments are leaf nodes in the navigation tree. But I do think I understand the issue,

**Comment by ericmgoeken** [comment]
Ok. Had some more time to look at it. I don't have a true fix for it, this change only works for one ReactView. If the back stack has a react screen then native screens it is fine, but if you put a react then react when you pop back it will destroy the instance manager and then look gesture tracking. 

https://github.com/ericmgoeken/react-native-android-fragment/commit/5abef1d485e94c436177fc930d4c89b37106f491

in ReactFragment.onDestroy we check
`reactInstanceMgr.getLifecycleState() != LifecycleState.RESUMED`

in my app the state is LifecycleState.BEFORE_RESUME so when your on the 2nd react view and you hit back it will destroy the instance manager. 

If I don't call 
```
reactInstanceMgr.onHostDestroy(getActivity());
getReactNativeHost().clear();
```
Then it works great, but that also means there is no clean up.

**Comment by jpshelley** [comment]
@ericmgoeken do you think a possible solution would be to modify the `onDestroy` to include:
 ```java
if (reactInstanceMgr.getLifecycleState() != LifecycleState.RESUMED
      && reactInstanceMgr.getLifecycleState() != LifecycleState.BEFORE_RESUME)) {
   /* teardown */
}
```

I wasn't aware of the BEFORE_RESUME prior to this issue. But maybe thats an acceptable solution?

**Comment by ericmgoeken** [comment]
Yes, that is related. Looking at BEFORE_RESUME works in my case, but I have not tested with react views only in a leaf. I have one react screen at the root so in my case it would never destroy.

**Comment by jpshelley** [comment]
We can create a manual test case in the example folder for this repo. At Hudl most of our React Native screens are leaf nodes, so if you push up a PR I can try it on our end as well.

**Comment by ericmgoeken** [comment]
PR created.

**Comment by ShaMan123** [comment]
I faced this strange error.
In my case the native android code was throwing an `IllegalArgumentException` that was silently mishandled. and of course android flagged a different error.
I saw that in this repo is using `IllegalArgumentException`.
Hope this helps!

**Comment by jpshelley** [comment]
@ericmgoeken Thanks for filing this issue. We'll be officially deprecating this repo now that Hudl has upgraded and can take advantage of `react-native`'s official [ReactFragment](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java)

If you believe the official `ReactFragment` also needs this support I would suggest opening a PR there! https://github.com/facebook/react-native/pulls
