### ISSUE TITLE
Dev tools support?

### ISSUE THREAD

**Issue by inakianduaga** [hudl/react-native-android-fragment#5]
I can't seem to get the RN dev tools appearing when using the fragment approach, is this something that is supported by this library? I'm doing the same approach that works for a standard RN activity add to AndroidManifest.xml:
```
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<application ...
...
  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
</application>
```

but it doesn't do anything

**Comment by jpshelley** [comment]
@inakianduaga Yes you are able to do that. We unfortunately forgot to add it to the example app so I'll try and submit a PR in the next few days to show how.
All you need to do is override your Activity's `onKeyUp` method and call into the ReactFragment's method https://github.com/hudl/react-native-android-fragment/blob/master/react-native-android-fragment/src/main/java/com/hudl/oss/react/fragment/ReactFragment.java#L235

We were hoping to minimize as many calls in the Activity as possible but some things we couldn't get around, unless others know of an easier way.

```java
    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        boolean handled = false;
        Fragment activeFragment = getSupportFragmentManager().findFragmentById(R.id.container);
        if (isReactNativeFragment(activeFragment)) {
            // isReactNativeFragment is a helper method to determine if it can be casted to ReactFragment
            handled = ((ReactFragment) activeFragment).onKeyUp(keyCode, event);
        }
        return handled || super.onKeyUp(keyCode, event);
    }

```
